name: ✨ Feature Request
description: Propose a new feature or enhancement
title: "[FEATURE]"
labels: enhancement
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the following details.
  - type: input
    id: feature_description
    attributes:
      label: Feature description
      description: Describe the feature you want to see implemented.
      placeholder: "A clear and concise description of the feature."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature would be useful or important.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you considered.
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
