name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build_and_test:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Connectiq.sln'
      
    permissions: 
      checks: write
      statuses: write
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
      
    - name: Add localhost certificate
      run: |
        echo "${{ secrets.LOCALHOST_CERT }}" | base64 -d > localhost.crt
        cat localhost.crt           # <-- este paso muestra el contenido para verificar
        sudo cp localhost.crt /usr/local/share/ca-certificates/localhost.crt
        sudo update-ca-certificates
        ls -l /etc/ssl/certs/localhost.crt
      shell: bash
      
    - name: List installed certificates
      run: sudo update-ca-certificates --verbose
      
    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.trx" || true
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
